# Generated by Django 5.2.8 on 2025-11-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regne', models.CharField(max_length=100)),
                ('embranchement', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('ordre', models.CharField(max_length=100)),
                ('famille', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('espece', models.CharField(max_length=100)),
                ('nom_vernaculaire', models.CharField(max_length=200)),
                ('partie_etat_indice', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField(blank=True, help_text="Date de la dernière mise à jour des résultats de recherche d'images", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=500)),
                ('file_format', models.CharField(max_length=100)),
                ('image_context_link', models.URLField(max_length=500)),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('image_byte_size', models.IntegerField()),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='taxons.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='taxons.taxon')),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'score'], name='taxons_user_session_9673c0_idx')],
                'unique_together': {('session_id', 'taxon')},
            },
        ),
    ]
