# Generated by Django 5.2.8 on 2026-04-23 20:08

from django.db import migrations


def clear_search_results(apps, schema_editor):
    SearchResult = apps.get_model("taxons", "SearchResult")
    SearchResult.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('taxons', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_search_results, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='searchresult',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='image_byte_size',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='image_width',
        ),
    ]
