# Generated by Django 5.2.8 on 2026-04-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxons', '0002_remove_google_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
